"""Base curada de unidades da PMMG para o autocompletar dos campos de
unidade no formulário (via <datalist> nativo).

Cada item é (valor, descricao): o VALOR é o que entra no documento (forma
curta, ex.: "34º BPM"); a DESCRICAO só aparece na sugestão do navegador.

NÃO é um registro oficial exaustivo - cobre as unidades estáveis e
conhecidas (comando, direção, ensino, corregedoria, comandos e batalhões
especializados, as 19 RPMs, batalhões numerados e companhias independentes).
Pelotões, destacamentos e frações específicas não cabem numa lista fixa;
por isso o campo aceita texto livre - o usuário digita a fração exata
quando não estiver nas sugestões.
"""

UNIDADES_PMMG = [
    ('Comando-Geral (CG)', 'Comando / Direção'),
    ('Estado-Maior da PMMG (EMPM)', 'Comando / Direção'),
    ('Gabinete do Comandante-Geral (GCG)', 'Comando / Direção'),
    ('Corregedoria da Polícia Militar (CPM)', 'Comando / Direção'),
    ('Ouvidoria da Polícia Militar', 'Comando / Direção'),
    ('Academia de Polícia Militar (APM)', 'Comando / Direção'),
    ('Centro de Pesquisa e Pós-Graduação (CPP)', 'Comando / Direção'),
    ('Escola de Formação e Aperfeiçoamento de Praças (EFAP)', 'Comando / Direção'),
    ('Centro de Treinamento Policial (CTP)', 'Comando / Direção'),
    ('Diretoria de Recursos Humanos (DRH)', 'Comando / Direção'),
    ('Diretoria de Apoio Logístico (DAL)', 'Comando / Direção'),
    ('Diretoria de Apoio Operacional (DAO)', 'Comando / Direção'),
    ('Diretoria de Saúde (DS)', 'Comando / Direção'),
    ('Diretoria de Finanças (DF)', 'Comando / Direção'),
    ('Diretoria de Educação Escolar e Assistência Social (DEEAS)', 'Comando / Direção'),
    ('Diretoria de Tecnologia e Sistemas (DTS)', 'Comando / Direção'),
    ('Diretoria de Inteligência (DINT)', 'Comando / Direção'),
    ('Centro Integrado de Comunicações Operacionais (CICOp)', 'Comando / Direção'),
    ('Comando de Policiamento Especializado (CPE)', 'Comando especializado'),
    ('Comando de Policiamento de Trânsito (CPTran)', 'Comando especializado'),
    ('Comando de Policiamento Rodoviário (CPRv)', 'Comando especializado'),
    ('Comando de Policiamento Ambiental (CPAmb)', 'Comando especializado'),
    ('Comando de Aviação (COMAV)', 'Comando especializado'),
    ('BOPE', 'Batalhão de Operações Policiais Especiais'),
    ('BPChoque', 'Batalhão de Polícia de Choque'),
    ('ROTAM', 'Rondas Táticas Metropolitanas'),
    ('BPRv', 'Batalhão de Polícia Militar Rodoviária'),
    ('BPMAmb', 'Batalhão de Polícia Militar de Meio Ambiente'),
    ('BPE', 'Batalhão de Polícia de Eventos'),
    ('BME', 'Batalhão de Missões Especiais'),
    ('BPMAr', 'Batalhão de Radiopatrulha Aérea'),
    ('BPTran', 'Batalhão de Trânsito'),
    ('RCAT', 'Regimento de Cavalaria Alferes Tiradentes'),
    ('Cia MEsp', 'Companhia de Missões Especiais'),
    ('1ª RPM', '1ª Região de Polícia Militar'),
    ('2ª RPM', '2ª Região de Polícia Militar'),
    ('3ª RPM', '3ª Região de Polícia Militar'),
    ('4ª RPM', '4ª Região de Polícia Militar'),
    ('5ª RPM', '5ª Região de Polícia Militar'),
    ('6ª RPM', '6ª Região de Polícia Militar'),
    ('7ª RPM', '7ª Região de Polícia Militar'),
    ('8ª RPM', '8ª Região de Polícia Militar'),
    ('9ª RPM', '9ª Região de Polícia Militar'),
    ('10ª RPM', '10ª Região de Polícia Militar'),
    ('11ª RPM', '11ª Região de Polícia Militar'),
    ('12ª RPM', '12ª Região de Polícia Militar'),
    ('13ª RPM', '13ª Região de Polícia Militar'),
    ('14ª RPM', '14ª Região de Polícia Militar'),
    ('15ª RPM', '15ª Região de Polícia Militar'),
    ('16ª RPM', '16ª Região de Polícia Militar'),
    ('17ª RPM', '17ª Região de Polícia Militar'),
    ('18ª RPM', '18ª Região de Polícia Militar'),
    ('19ª RPM', '19ª Região de Polícia Militar'),
    ('1º BPM', '1º Batalhão de Polícia Militar'),
    ('2º BPM', '2º Batalhão de Polícia Militar'),
    ('3º BPM', '3º Batalhão de Polícia Militar'),
    ('4º BPM', '4º Batalhão de Polícia Militar'),
    ('5º BPM', '5º Batalhão de Polícia Militar'),
    ('6º BPM', '6º Batalhão de Polícia Militar'),
    ('7º BPM', '7º Batalhão de Polícia Militar'),
    ('8º BPM', '8º Batalhão de Polícia Militar'),
    ('9º BPM', '9º Batalhão de Polícia Militar'),
    ('10º BPM', '10º Batalhão de Polícia Militar'),
    ('11º BPM', '11º Batalhão de Polícia Militar'),
    ('12º BPM', '12º Batalhão de Polícia Militar'),
    ('13º BPM', '13º Batalhão de Polícia Militar'),
    ('14º BPM', '14º Batalhão de Polícia Militar'),
    ('15º BPM', '15º Batalhão de Polícia Militar'),
    ('16º BPM', '16º Batalhão de Polícia Militar'),
    ('17º BPM', '17º Batalhão de Polícia Militar'),
    ('18º BPM', '18º Batalhão de Polícia Militar'),
    ('19º BPM', '19º Batalhão de Polícia Militar'),
    ('20º BPM', '20º Batalhão de Polícia Militar'),
    ('21º BPM', '21º Batalhão de Polícia Militar'),
    ('22º BPM', '22º Batalhão de Polícia Militar'),
    ('23º BPM', '23º Batalhão de Polícia Militar'),
    ('24º BPM', '24º Batalhão de Polícia Militar'),
    ('25º BPM', '25º Batalhão de Polícia Militar'),
    ('26º BPM', '26º Batalhão de Polícia Militar'),
    ('27º BPM', '27º Batalhão de Polícia Militar'),
    ('28º BPM', '28º Batalhão de Polícia Militar'),
    ('29º BPM', '29º Batalhão de Polícia Militar'),
    ('30º BPM', '30º Batalhão de Polícia Militar'),
    ('31º BPM', '31º Batalhão de Polícia Militar'),
    ('32º BPM', '32º Batalhão de Polícia Militar'),
    ('33º BPM', '33º Batalhão de Polícia Militar'),
    ('34º BPM', '34º Batalhão de Polícia Militar'),
    ('35º BPM', '35º Batalhão de Polícia Militar'),
    ('36º BPM', '36º Batalhão de Polícia Militar'),
    ('37º BPM', '37º Batalhão de Polícia Militar'),
    ('38º BPM', '38º Batalhão de Polícia Militar'),
    ('39º BPM', '39º Batalhão de Polícia Militar'),
    ('40º BPM', '40º Batalhão de Polícia Militar'),
    ('41º BPM', '41º Batalhão de Polícia Militar'),
    ('42º BPM', '42º Batalhão de Polícia Militar'),
    ('43º BPM', '43º Batalhão de Polícia Militar'),
    ('44º BPM', '44º Batalhão de Polícia Militar'),
    ('45º BPM', '45º Batalhão de Polícia Militar'),
    ('46º BPM', '46º Batalhão de Polícia Militar'),
    ('47º BPM', '47º Batalhão de Polícia Militar'),
    ('48º BPM', '48º Batalhão de Polícia Militar'),
    ('49º BPM', '49º Batalhão de Polícia Militar'),
    ('50º BPM', '50º Batalhão de Polícia Militar'),
    ('51º BPM', '51º Batalhão de Polícia Militar'),
    ('52º BPM', '52º Batalhão de Polícia Militar'),
    ('53º BPM', '53º Batalhão de Polícia Militar'),
    ('54º BPM', '54º Batalhão de Polícia Militar'),
    ('55º BPM', '55º Batalhão de Polícia Militar'),
    ('1ª Cia PM Ind', '1ª Companhia de Polícia Militar Independente'),
    ('2ª Cia PM Ind', '2ª Companhia de Polícia Militar Independente'),
    ('3ª Cia PM Ind', '3ª Companhia de Polícia Militar Independente'),
    ('4ª Cia PM Ind', '4ª Companhia de Polícia Militar Independente'),
    ('5ª Cia PM Ind', '5ª Companhia de Polícia Militar Independente'),
    ('6ª Cia PM Ind', '6ª Companhia de Polícia Militar Independente'),
    ('7ª Cia PM Ind', '7ª Companhia de Polícia Militar Independente'),
    ('8ª Cia PM Ind', '8ª Companhia de Polícia Militar Independente'),
    ('9ª Cia PM Ind', '9ª Companhia de Polícia Militar Independente'),
    ('10ª Cia PM Ind', '10ª Companhia de Polícia Militar Independente'),
    ('11ª Cia PM Ind', '11ª Companhia de Polícia Militar Independente'),
    ('12ª Cia PM Ind', '12ª Companhia de Polícia Militar Independente'),
    ('13ª Cia PM Ind', '13ª Companhia de Polícia Militar Independente'),
    ('14ª Cia PM Ind', '14ª Companhia de Polícia Militar Independente'),
    ('15ª Cia PM Ind', '15ª Companhia de Polícia Militar Independente'),
    ('16ª Cia PM Ind', '16ª Companhia de Polícia Militar Independente'),
    ('17ª Cia PM Ind', '17ª Companhia de Polícia Militar Independente'),
    ('18ª Cia PM Ind', '18ª Companhia de Polícia Militar Independente'),
    ('19ª Cia PM Ind', '19ª Companhia de Polícia Militar Independente'),
    ('20ª Cia PM Ind', '20ª Companhia de Polícia Militar Independente'),
]
